
- platform: template
  sensors:
## Deprecated - Is now determined based on scene input select
#    display_commute:
#      friendly_name: Display Commute Card
#      entity_id: input_select.scene
#      value_template: >
#          {% set ct = now().hour + now().minute/60 + now().second/3600 %}
#          {{ 6 <= ct <= 12 and now().weekday() < 5 }}

    next_alarm_within15min:
      value_template: >
        {% if states('sensor.next_alarm') != "None" %}
          {{ (states('sensor.next_alarm')|int/1000) - as_timestamp(now()) < 900 }}
        {% else %}
          False
        {% endif %}
      friendly_name: Next alarm within 15 minutes
      icon_template: 'mdi:alarm'
      entity_id: sensor.time