homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  unit_system: metric
  time_zone: CET
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml

system_health:
mobile_app:
  
http:
  base_url: !secret baseurl
  ip_ban_enabled: True
  login_attempts_threshold: 5

recorder:
  purge_keep_days: 3
  purge_interval: 1
  exclude:
    domains:
      - automation
      - scene
      - script
      - zone

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxpass
  max_retries: 3
  default_measurement: state

updater:
   include_used_components: true

discovery:
  ignore:
    - yeelight
    
config:
ios:
history:
logbook:
map:
sun:

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
google_assistant: !include google_assistant.yaml
scene: !include scenes.yaml

tts:
  - platform: google_translate
    service_name: google_say
    cache: false
    base_url: http://192.168.1.100:8123

input_select:
  scene:
    name: 'Scene'
    icon: mdi:theme-light-dark
    options:
    - "Morning"
    - "Day"
    - "Evening"
    - "Night"

input_boolean:
  party_mode:
    name: "Party Mode!"
    initial: off
    icon: mdi:balloon

input_number:
  max_sun_elevation_decrease:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Max sun elevation decrease (%)
    step: 1
    unit_of_measurement: "%"
  morning_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Morning when elevation reaches
    step: 0.5
    unit_of_measurement: "°"
  day_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Day when elevation reaches
    step: 0.5
    unit_of_measurement: "°"
  afternoon_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Afternoon when elevation drops below
    step: 0.5
    unit_of_measurement: "°"
  early_evening_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Early evening when elevation drops below
    step: 0.5
    unit_of_measurement: "°"
  evening_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Evening when elevation drops below
    step: 0.5
    unit_of_measurement: "°"

weather:
  - platform: buienradar
    name: buienradar

zone:
  - name: Work
    latitude: 52.336963
    longitude: 4.861719
    radius: 100
    icon: mdi:briefcase
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home

device_tracker:
  - platform: bluetooth_tracker
    track_new_devices: false
  - platform: nmap_tracker
    hosts: 192.168.1.50-255
    exclude:
    - 192.168.1.100
    track_new_devices: false
    consider_home: 300

media_player:
  - platform: spotify
    client_id: !secret spotifyid
    client_secret: !secret spotifysecret

yeelight:
  devices:
    192.168.1.200:
      name: HallwayCeiling
      model: color2
      save_on_change: true
    192.168.1.201:
      name: Livingroom
      model: color2
      save_on_change: true
    192.168.1.203:
      name: Bedroom
      model: color1
      save_on_change: true
    192.168.1.204:
      name: Toilet
      model: color1
      save_on_change: true
  custom_effects:
    - name: 'Wakeuplight'
      flow_params:
        count: 1
        action: stay
        transitions:
          - RGBTransition: [255, 0, 0, 300000, 1]
          - RGBTransition: [253, 106, 2, 900000, 50]
          - TemperatureTransition: [3000, 600000, 80]

light:
  - platform: nanoleaf
    host: 192.168.1.205
    token: !secret nanoleaftoken
  - platform: mqtt
    schema: json
    name: Living room spots
    command_topic: "zigbee2mqtt/livingroom_spotlights/set"
    state_topic: "zigbee2mqtt/livingroom_spotlights"
    color_temp: true
    brightness: true
    rgb: false
  - platform: switch
    name: Terrarium Light
    entity_id: switch.terrarium_switch

hacs:
  token: 248eb171ef27e307ad3e1adbe19d02b9d7c074c9
  appdaemon: True
  python_script: True
  theme: True

circadian_lighting:
  min_colortemp: 2250
  max_colortemp: 5000
  # interval: 900
  # transition: 900

# plant:
#   dieffenbachia:
#     sensors:
#       moisture: sensor.dieffenbachia_moisture
#       battery: sensor.dieffenbachia_battery
#       temperature: sensor.dieffenbachia_temperature
#       conductivity: sensor.dieffenbachia_conductivity
#       brightness: sensor.dieffenbachia_light_intensity
#     min_moisture: 15
#     max_moisture: 60
#     min_conductivity: 200
#     max_conductivity: 1500
#     min_temperature: 12
#     max_temperature: 32
#     min_brightness: 1500
#     max_brightness: 25000
#     min_battery: 10


switch:
  - platform: circadian_lighting
    lights_ct:
      - light.livingroom
      - light.livingroom_spot1_light
      - light.livingroom_spot2_light
      - light.livingroom_spot3_light
      - light.livingroom_spot4_light
      - light.living_room_spots
      - light.bedroom
    lights_brightness:
      - light.nanoleaf
  - platform: broadlink
    host: 192.168.1.202
    mac: '78:0F:77:5A:B5:02'
    friendly_name: Universal Remote
    type: rm_mini
    switches:
      soundbar:
        friendly_name: "LG Sound Bar"
        command_on:
          'JgBWAJeSFBEUERQ1FDYUERQ2FBEUERQRFBEUNhQ2FBETNhQRFBEUERQ2FDYUNhQ1FREUERMSEzYUERQRFBEUERQ2FDYUNhQABgaXkhQ2FAAMX5aTFDYUAA0FAAA='
        command_off:
          'JgBWAJeSFBEUERQ1FDYUERQ2FBEUERQRFBEUNhQ2FBETNhQRFBEUERQ2FDYUNhQ1FREUERMSEzYUERQRFBEUERQ2FDYUNhQABgaXkhQ2FAAMX5aTFDYUAA0FAAA='
      tv_samsung:
        friendly_name: "Samsung TV"
        command_on:
          'JgBGAJaTFDYVNxQ2FRIVERUSFREVEhU1FjYVNhUSFBIVEhQSFRISOBYSFBIVNhU2FRIVERU3FBEWNhU2FRIUEhU3FDYVEhUADQUAAA=='
        command_off:
          'JgBGAJSWEzcUOBQ3FBIUERQTEhIUExI4EzkTNxUSExIUEhMSFBIUERQTExEVNxQ3FBITEhQ4EzcUOBM3FBITEhQ4EzcVEhMADQUAAA==' 
      vacuum:
        friendly_name: Deebot Vacuum Cleaner
        command_on:
          'JgBQAAABKpEVEBQRFBEUEBUQFRAUERQRFDUVNRQ1FTUVNRQ1FTUUNRUQFTUUERQ1FRAVEBQRFBAVNRUQFDUVEBU1FDUVNRU1FAAFJgABKkgVAA0FAAAAAAAAAAA='
        command_off:
          'JgBQAAABKZIUERQRFBEUEBUQFBEUERQRFDUVNRQ1FTUUNhQ1FTUUNRUQFTUUNRU1FBEUERQQFRAVNRQRFBAVEBU1FDUVNRQ2FAAFJgABKkgVAA0FAAAAAAAAAAA='