homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  unit_system: metric
  time_zone: CET
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

panel_iframe:
  grafana:
    title: 'Grafana'
    icon: mdi:monitor-dashboard
    url: 'https://grafana.home/d/X-6T2Ymgz/dash?orgId=1&refresh=10s&from=now-24h&to=now&kiosk'

system_health:
mobile_app:
  
http:
  ip_ban_enabled: True
  login_attempts_threshold: 5

recorder:
  purge_keep_days: 3
  exclude:
    domains:
      - automation
      - scene
      - script
      - zone

influxdb:
  host: 192.168.2.100
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxpass
  max_retries: 3
  default_measurement: state

updater:
   include_used_components: true

discovery:
  ignore:
    - yeelight
    
config:
ios:
history:
logbook:
map:
sun:

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
google_assistant: !include google_assistant.yaml
scene: !include scenes.yaml

tts:
  - platform: google_translate
    service_name: google_say
    cache: false
    base_url: http://192.168.2.100:8123

input_select:
  scene:
    name: 'Scene'
    icon: mdi:theme-light-dark
    options:
    - "Morning"
    - "Day"
    - "Evening"
    - "Night"

input_boolean:
  party_mode:
    name: "Party Mode!"
    initial: off
    icon: mdi:balloon

input_number:
  max_sun_elevation_decrease:
    icon: mdi:tune
    max: 100
    min: 0
    mode: box
    name: Max sun elevation decrease (%)
    step: 1
    unit_of_measurement: "%"
  morning_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Morning when elevation reaches
    step: 0.5
    unit_of_measurement: "°"
  day_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Day when elevation reaches
    step: 0.5
    unit_of_measurement: "°"
  afternoon_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Afternoon when elevation drops below
    step: 0.5
    unit_of_measurement: "°"
  early_evening_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Early evening when elevation drops below
    step: 0.5
    unit_of_measurement: "°"
  evening_threshold:
    icon: mdi:tune
    max: 10
    min: -10
    mode: box
    name: Activate Evening when elevation drops below
    step: 0.5
    unit_of_measurement: "°"

weather:
  - platform: buienradar
    name: buienradar

zone:
  - name: Work
    latitude: 52.336963
    longitude: 4.861719
    radius: 100
    icon: mdi:briefcase
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home

device_tracker:
  - platform: bluetooth_tracker
    track_new_devices: false

spotify:
  client_id: !secret spotifyid
  client_secret: !secret spotifysecret

media_player:
  - platform: philips_android_tv
    name: Philips TV
    host: !secret philipsTV_host
    mac: !secret philipsTV_mac
    username: !secret philipsTV_username
    password: !secret philipsTV_password

pi_hole:
  - host: !secret pihole_host

yeelight:
  devices:
    192.168.3.201:
      name: Bedroom
      model: color1
      save_on_change: true
    192.168.3.202:
      name: Toilet
      model: color1
      save_on_change: true
    192.168.3.203:
      name: HallwayCeiling
      model: color2
      save_on_change: true
    192.168.3.204:
      name: Livingroom
      model: color2
      save_on_change: true
  custom_effects:
    - name: 'Wakeuplight'
      flow_params:
        count: 1
        action: stay
        transitions:
          - RGBTransition: [255, 0, 0, 300000, 1]
          - RGBTransition: [253, 106, 2, 900000, 50]
          - TemperatureTransition: [3000, 600000, 80]

light:
  - platform: nanoleaf
    host: 192.168.3.205
    token: !secret nanoleaftoken
  - platform: mqtt
    schema: json
    name: Living room spots
    command_topic: "zigbee2mqtt/livingroom_spotlights/set"
    state_topic: "zigbee2mqtt/livingroom_spotlights"
    color_temp: true
    brightness: true
    rgb: false
  - platform: switch
    name: Terrarium Light
    entity_id: switch.terrarium_switch
  - platform: philips_ambilight
    name: Ambilight
    host: !secret philipsTV_host
    username: !secret philipsTV_username
    password: !secret philipsTV_password

circadian_lighting:
  min_colortemp: 2250
  max_colortemp: 5000

# stream:
# camera:
#   - platform: generic
#     name: YiCam
#     still_image_url: "http://192.168.1.55:8080/cgi-bin/snapshot.sh"
#     framerate: 1
#     #stream_source: !secret yicam_stream
#     verify_ssl: false
#     username: !secret yicam_user
#     password: !secret yicam_pass

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: Telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

switch:
  - platform: circadian_lighting
    lights_ct:
      - light.livingroom
      - light.livingroom_spot1_light
      - light.livingroom_spot2_light
      - light.livingroom_spot3_light
      - light.livingroom_spot4_light
      - light.living_room_spots
    lights_brightness:
      - light.nanoleaf
  - platform: broadlink
    host: 192.168.3.200
    mac: '78:0F:77:5A:B5:02'
    friendly_name: Universal Remote
    type: rm_mini
    switches:
      soundbar:
        friendly_name: "LG Sound Bar"
        command_on:
          'JgBWAJeSFBEUERQ1FDYUERQ2FBEUERQRFBEUNhQ2FBETNhQRFBEUERQ2FDYUNhQ1FREUERMSEzYUERQRFBEUERQ2FDYUNhQABgaXkhQ2FAAMX5aTFDYUAA0FAAA='
        command_off:
          'JgBWAJeSFBEUERQ1FDYUERQ2FBEUERQRFBEUNhQ2FBETNhQRFBEUERQ2FDYUNhQ1FREUERMSEzYUERQRFBEUERQ2FDYUNhQABgaXkhQ2FAAMX5aTFDYUAA0FAAA='
      vacuum:
        friendly_name: Deebot Vacuum Cleaner
        command_on:
          'JgBQAAABKpEVEBQRFBEUEBUQFRAUERQRFDUVNRQ1FTUVNRQ1FTUUNRUQFTUUERQ1FRAVEBQRFBAVNRUQFDUVEBU1FDUVNRU1FAAFJgABKkgVAA0FAAAAAAAAAAA='
        command_off:
          'JgBQAAABKZIUERQRFBEUEBUQFBEUERQRFDUVNRQ1FTUUNhQ1FTUUNRUQFTUUNRU1FBEUERQQFRAVNRQRFBAVEBU1FDUVNRQ2FAAFJgABKkgVAA0FAAAAAAAAAAA='