- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: dsmr
  port: /dev/ttyUSB0
  dsmr_version: 5

- platform: miflora
  mac: C4:7C:8D:6A:6E:1F
  name: Dieffenbachia
  median: 1
- platform: miflora
  mac: C4:7C:8D:6A:84:01
  name: Backup Miflora
  median: 1

- platform: waqi
  token: !secret aqitoken
  locations:
  - 'utrecht'
  stations:
  - 'de Jongweg, Utrecht'

- platform: rest
  name: Next alarm
  resource: http://192.168.1.208:8008/setup/assistant/alarms
  value_template: >
    {% set alarms = value_json.alarm|sort(attribute='fire_time') %}
    {% if alarms[0] is defined %}
      {{ alarms[0].fire_time }}
    {% else %}
      None
    {% endif %}

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: load_5m
  - type: processor_use
  - type: last_boot
  
- platform: waze_travel_time
  origin: !secret homeaddr
  destination: !secret workaddr
  region: 'EU'
  name: "Work commute"
- platform: waze_travel_time
  origin: !secret workaddr
  destination: !secret homeaddr
  region: 'EU'
  name: "Home commute"

- platform: template
  sensors:
    next_alarm_human:
      value_template: >
        {% if states('sensor.next_alarm') == "None" %}
          No alarm set
        {% elif states('sensor.next_alarm') == "unavailable" %}
          Google Home unavailable
        {% else %}
          {{ (states('sensor.next_alarm')|int/1000)|timestamp_custom('%A %H:%M') }}
        {% endif %}
      friendly_name: Next alarm
      icon_template: 'mdi:alarm'

    totalpowerconsumption:
      value_template: '{{ ( states("sensor.power_consumption_low")|float ) + ( states("sensor.power_consumption_normal")|float ) }}'
      friendly_name: Total power consumption
      unit_of_measurement: 'kWh'
      icon_template: 'mdi:power-socket-eu'
      
    buienradar_temperature:
      value_template: '{{ states.weather.buienradar.attributes.temperature }}'
      device_class: temperature
      friendly_name: Temperature outside
      unit_of_measurement: '°C'
      
    buienradar_pressure:
      value_template: '{{ states.weather.buienradar.attributes.pressure }}'
      device_class: pressure
      friendly_name: Pressure outside
      unit_of_measurement: 'hPa'
      
    buienradar_humidity:
      value_template: '{{ states.weather.buienradar.attributes.humidity }}'
      device_class: humidity
      friendly_name: Humidity outside
      unit_of_measurement: '%'
