- platform: dsmr
  port: /dev/ttyUSB0
  dsmr_version: 5

- platform: waqi
  token: !secret aqitoken
  locations:
  - 'utrecht'
  stations:
  - 'de Jongweg, Utrecht'

### Todo - verify correct (/both) alarm source
- platform: rest
    resource: http://192.168.1.56:8008/setup/assistant/alarms
    value_template: "{{ value_json.alarm.0.fire_time }}"
    name: Next alarm

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: load_5m
  - type: processor_use
  - type: last_boot
  
- platform: template
  sensors:
    buienradar_temperature:
      value_template: '{{ states.weather.buienradar.attributes.temperature }}'
      device_class: temperature
      friendly_name: Outside temperature
    buienradar_pressure:
      value_template: '{{ states.weather.buienradar.attributes.pressure }}'
      device_class: pressure
      friendly_name: Outside pressure
    buienradar_humidity:
      value_template: '{{ states.weather.buienradar.attributes.humidity }}'
      device_class: humidity
      friendly_name: Outside humidity
    climatesensor_battery:
      value_template: '{{ states.sensor.climatesensor_temperature.attributes.battery }}'
      device_class: battery
      friendly_name: Climate sensor battery
    motionsensor_hallway_battery:
      value_template: '{{ states.sensor.motionsensor_hallway_illuminance.attributes.battery }}'
      device_class: battery
      friendly_name: Hallway motion sensor battery
    motionsensor_toilet_battery:
      value_template: '{{ states.sensor.motionsensor_toilet_illuminance.attributes.battery }}'
      device_class: battery
      friendly_name: Toilet motion sensor battery
    xiaomibutton_battery:
      value_template: '{{ states.sensor.xiaomibutton.attributes.battery }}'
      device_class: battery
      friendly_name: Xiaomi button battery
    xiaomiswitch_battery:
      value_template: '{{ states.sensor.xiaomiswitch1_2.attributes.battery }}'
      device_class: battery
      friendly_name: Xiaomi switch battery
